#!/bin/sh

# "Forbidden" regular expressions
DEBUGGING=('console\.debug' 'console\.log' 'binding\.pry' 'binding\.remote_pry' 'save_and_open_page' 'debugger')
MERGE_CONFLICT=('^>>>>>>' '^<<<<<<' '^======')

# Loop over ALL errors and warnings and return ALL problems.
# I want to report on *all* problems that exist in the commit before aborting,
# so that anyone calling --no-verify has been informed of all problems first.
ERROR=false

for FILE in `git diff --cached --name-only`; do
  for DEBUG in ${DEBUGGING[*]}; do
    if grep -iqe $DEBUG $FILE; then
      echo "Warning: found debug statement '$DEBUG'"
      echo "   File: $FILE\n--------------"
      ERROR=true
    fi
  done
  for CONFLICT in ${MERGE_CONFLICT[*]}; do
    if grep -iqe $CONFLICT $FILE; then
      echo "Error: found merge conflict"
      echo " File: $FILE\n--------------"
      ERROR=true
    fi
  done
done

if [ $ERROR == true ]; then
  echo "To commit anyway, use --no-verify"
  exit 1
fi
