#!/bin/sh

# "Forbidden" regular expressions
DEBUGGING=('binding\.pry' 'binding\.remote_pry' 'save_and_open_page' 'debugger')

# Loop over ALL errors and warnings and return ALL problems.
# I want to report on *all* problems that exist in the commit before aborting,
# so that anyone calling --no-verify has been informed of all problems first.
ERROR=false

for FILE in `git diff --cached --name-only`; do
  if [ -e $FILE ]; then
    if [ ${FILE: -3} == '.rb' ]; then
      for DEBUG in ${DEBUGGING[*]}; do
        if grep -iqe $DEBUG $FILE; then
          echo "Warning: found debug statement '$DEBUG'"
          echo "   File: $FILE\n--------------"
          ERROR=true
        fi
      done

      spec_file=${FILE%%_spec.rb}
      if [ ${spec_file} != ${FILE} ]; then
        if grep -iqe 'focus' $FILE; then
          echo "Warning: found focus statement in specs"
          echo "   File: $FILE\n--------------"
          ERROR=true
        fi
      fi
    fi
  fi
done

# if [ $ERROR == true ]; then
  echo "To commit anyway, use --no-verify"
  exit 1
# fi
