#!/bin/bash

SCRIPTPATH=$(pwd)
cd $SCRIPTPATH

ACTION=$1
ARGS=$2

if [ -z $ACTION ]; then
  ACTION="dotfiles"
fi

if [ $ACTION != "all" ]; then
  . "$SCRIPTPATH/scripts/$ACTION" $ARGS
else
  . "$SCRIPTPATH/scripts/packages"
  . "$SCRIPTPATH/scripts/dotfiles" O
  . "$SCRIPTPATH/scripts/vim"
  . "$SCRIPTPATH/scripts/vim-node-modules"
  . "$SCRIPTPATH/scripts/neovim"
  . "$SCRIPTPATH/scripts/asdf"
  . "$SCRIPTPATH/scripts/rbenv"
  . "$SCRIPTPATH/scripts/zsh"
  . "$SCRIPTPATH/scripts/solarized"
fi

sudo -k
