#!/bin/bash

if [ ! -d ~/.rbenv ]; then
  echo "Installing rbenv"
  git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
  source ~/.profile
  exec $SHELL -l
fi

mkdir -p ~/.rbenv/plugins
if [ ! -d ~/.rbenv/plugins/ruby-build ]; then
  echo "Installing ruby-build"
  git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

echo "Installing ruby 1.9.3"
rbenv install 1.9.3-p327
rbenv rehash
rbenv global 1.9.3-p327

if [ ! -d ~/.rbenv/plugins/rbenv-ctags ]; then
  echo "Installing rbenv-ctags"
  git clone git://github.com/tpope/rbenv-ctags.git ~/.rbenv/plugins/rbenv-ctags
  rbenv ctags
fi

gem install bundler
bundle install
gem ctags
