#!/usr/bin/env bash

SCRIPTPATH=$(pwd)
cd "$SCRIPTPATH" || return

ACTION=$1
ARGS=$2

./scripts/banner "Starting Install"

if [ -z "$ACTION" ]; then
  . "$SCRIPTPATH"/scripts/chezmoi
  . "$SCRIPTPATH"/scripts/solarized
  . "$SCRIPTPATH"/scripts/asdf
  . "$SCRIPTPATH"/scripts/vim-node-modules
  . "$SCRIPTPATH"/scripts/neovim
  . "$SCRIPTPATH"/scripts/lunarvim
  . "$SCRIPTPATH"/scripts/tmux
  . "$SCRIPTPATH"/scripts/iterm2
else
  . "$SCRIPTPATH"/scripts/"$ACTION" $ARGS
fi

if command -v sudo &> /dev/null; then
  sudo -k
fi

./scripts/banner "Install Finished"
