#!/bin/bash

SCRIPTPATH=`pwd -P`
echo "Changing directory to $SCRIPTPATH"
cd $SCRIPTPATH

for linkable in `find $SCRIPTPATH -name "*.symlink"`
do
  file=$(basename "$linkable" .symlink)
  target="$HOME/$file"

  # Remove all symlinks created during installation
  if [ -L $target ]; then
    rm -v "$target"
  fi

  # Replace any backups made during installation
  if [ -e "$target.backup" ]; then
    echo "moving $target.backup to $file"
    mv -v "$target.backup" "$target"
  fi

done
