#!/bin/env sh

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
# umask 022

export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
if [ "$(uname)" = "Darwin" ]; then
  export PATH="/usr/local/opt/binutils/bin:$PATH"
  export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/curl/bin:$PATH"
  export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
  export PATH="/usr/local/opt/gnu-indent/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/gnu-time/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/gnu-which/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
  export PATH="/usr/local/opt/ncurses/bin:$PATH"
  export PATH="/usr/local/opt/ssh-copy-id/bin:$PATH"

  export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
  export MANPATH="/usr/local/opt/findutils/libexec/gnuman:$MANPATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
  export PATH="$HOME/bin:$PATH"
fi

export PATH="$PATH:$HOME/.local/bin"

export PAGER="bat"
export EDITOR="nvim"
export VISUAL="nvim"
export LESS="-iFRSXJMQ"

# Git PS1
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWSTASHSTATE=true

# export JAVA_OPTS="-Xms1024m -Xmx2048m -XX:PermSize=32m -XX:MaxPermSize=512m -Xss2m"

export KEYTIMEOUT=1

if [ -f "$HOME/.ssh/id_rsa" ]; then
  if command -v keychain >/dev/null; then
    eval "$(keychain --eval --quiet --quick)"
  fi
fi

if [ -d "/usr/local/opt/go/libexec/bin" ]; then
  export PATH="$PATH:/usr/local/opt/go/libexec/bin"
fi

# Be higher so that command -v blah picks up things from asdf
if [ -d "$HOME/.asdf" ]; then
  source "$HOME"/.asdf/asdf.sh
fi

if command -v go >/dev/null; then
  export GO111MODULE=auto
  if [ -d "$HOME/go" ]; then
    if [ -z "$GOPATH" ]; then
      export GOPATH="$HOME/go"
    fi
    export PATH="$PATH:$GOPATH/bin"
  fi
fi

if command -v fasd >/dev/null; then
  fasd_cache="$HOME/.fasd-init-cache"
  if [ ! -f "$fasd_cache" ]; then
    fasd --init auto >|"$fasd_cache"
  fi
  . "$fasd_cache"
  unset fasd_cache
fi

if [ -d "$HOME/.rd/bin" ]; then
  export PATH="$HOME/.rd/bin:$PATH"
fi

if command -v cargo >/dev/null; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

# only define LC_CTYPE if undefined
if [ -z "$LC_CTYPE" ] && [ -z "$LC_ALL" ]; then
  export LC_CTYPE="${LANG%%:*}" # pick the first entry from LANG
fi

# if running bash
if [ -n "$BASH_VERSION" ]; then
  # include .bashrc if it exists
  if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi

export COLORTERM=truecolor
export CLICOLOR=1

export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

export BAT_CONFIG_PATH="$HOME/.bat"

export ERL_AFLAGS="-kernel shell_history enabled"

export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'

export GPG_TTY=$(tty)

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

export ASDF_GOLANG_MOD_VERSION_ENABLED=false

lombok_jar="$HOME/.local/share/nvim/mason/packages/jdtls/lombok.jar"
if [ -f $lombok_jar ]; then
  export JDTLS_JVM_ARGS="-javaagent:$lombok_jar"
fi

if [ -f "$HOME/.profile.local" ]; then
  . "$HOME/.profile.local"
fi
