return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        -- "actionlint",
        -- "ast-grep",
        -- "awk-language-server",
        -- "bash-debug-adapter",
        -- "bash-language-server",
        -- "black",
        -- "checkstyle",
        -- "cmakelang",
        -- "cmakelint",
        -- "codespell",
        -- "commitlint",
        -- "cspell",
        -- "css-lsp",
        -- "delve",
        -- "docker-compose-language-service",
        -- "dockerfile-language-server",
        -- "editorconfig-checker",
        -- "eslint-lsp",
        -- "flake8",
        -- "goimports",
        -- "gopls",
        -- "graphql-language-service-cli",
        -- "hadolint",
        -- "html-lsp",
        -- "java-debug-adapter",
        -- "java-debug-adapter",
        -- "jdtls",
        -- "jq",
        -- "jq-lsp",
        -- "js-debug-adapter",
        -- "json-lsp",
        -- "jsonld-lsp",
        -- "jsonlint",
        -- "lua-language-server",
        -- "luacheck",
        -- "markdownlint",
        -- "marksman",
        -- "misspell",
        -- "neocmakelsp",
        -- "prettier",
        -- "pyright",
        -- "ripper-tags",
        -- "rubocop",
        -- "ruby-lsp",
        -- "semgrep",
        -- "shellcheck",
        -- "shellharden",
        -- "shfmt",
        -- "shfmt",
        -- "snyk-ls",
        -- "solargraph",
        -- "sonarlint-language-server",
        -- "sorbet",
        -- "spectral-language-server",
        -- "sql-formatter",
        -- "sqlfmt",
        -- "sqlls",
        -- "staticcheck",
        -- "stylua",
        -- "stylua",
        -- "tailwindcss-language-server",
        -- "taplo",
        -- "terraform-ls",
        -- "tflint",
        "tree-sitter-cli",
        -- "trivy",
        -- "typescript-language-server",
        -- "typos",
        -- "typos-lsp",
        -- "vacuum",
        -- "vim-language-server",
        -- "xmlformatter",
        -- "yaml-language-server",
        -- "yamlfix",
        -- "yamlfmt",
        -- "yamllint",
        -- "yq",
      },
    },
  },
}
