return {
  {
    "williamboman/mason.nvim",
    lazy = true,
    opts = function(_, opts)
      vim.list_extend(opts.ensure_installed, {
        "tree-sitter-cli",
        -- "bashls",
        -- "biome",
        -- "cmake-language-server",
        -- "cssls",
        -- "diagnosticls",
        -- "docker_compose_language_service",
        -- "dockerls",
        -- "dotls",
        -- "eslint",
        -- "gradle_ls",
        -- "graphql",
        -- "helm_ls",
        -- "cspell",
        -- "html",
        -- "jq",
        -- "jsonls",
        -- "marksman",
        -- "pyright",
        -- "rubocop",
        -- "ruby_lsp",
        -- "solargraph",
        -- "somesass_ls",
        -- "sqlls",
        -- "standardrb",
        -- "taplo",
        -- "terraformls",
        -- "tflinit",
        -- "tsserver",
        -- "tsserver",
        -- "yamlls",
      })
    end,
  },
}
