#!/usr/bin/env bash

set -e

./scripts/banner "Processing dotfiles"

current_script="${BASH_SOURCE}[0]"
current_dir=$(dirname "$current_script")
root_dir=$(dirname "$current_dir")
stow_dir="$root_dir/stow"
packages=($( ls -A  -1 $stow_dir))


files=($(find stow -type f))
for file in "${files[@]}"
do
  target="$HOME/$(sed 's/stow\/.*\///g' <<< "$file")"

  if [ -L "$target" ] || [ -f "$target" ]; then
    echo "File already exists: $target, what do you want to do? [s]kip, [o]verwrite, [a]bort]"
    read -r response
    case "$response" in
      a) exit 1 ;;
      s) echo "skipping $target" && continue ;;
    esac

    cp -v "$target" "$target.backup"
    rm -v "$target"
  fi
done

for package in "${packages[@]}"
do
  echo "stowing $package"
  stow -R -v --no-folding --adopt -d "$stow_dir" -t "$HOME" -S "$package"
done

git checkout $stow_dir

ln -vnsf "$HOME/.profile" "$HOME/.zprofile"

source "$HOME/.profile"
