#!/usr/bin/env bash

set -e

./scripts/banner "Processing iterm2"

if [ -n "$ITERM_PROFILE" ] ; then
  echo "Downloading iterm2 color themes..."
  wget -nc0 https://raw.githubusercontent.com/JonathanSpeek/palenight-iterm2/master/palenight.itermcolors ~/Downloads/palenight.itermcolors
  echo "Open Iterm \`Settings, Profiles, Colors\` and import the color themes downloaded in ~/Downloads"
fi
