#!/usr/bin/env bash

if [ -n "$ITERM_PROFILE" ] ; then
  echo "Downloading iterm2 color themes..."
  cd ~/Downloads || return
  wget -nc https://raw.githubusercontent.com/JonathanSpeek/palenight-iterm2/master/palenight.itermcolors
  echo "Open Iterm \`Settings, Profiles, Colors\` and import the color themes downloaded in ~/Downloads"
fi
