#!/usr/bin/env bash

set -e

echo "Processing lunarvim"

if ! command -v lvim > /dev/null; then
  bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
fi
