#!/usr/bin/env bash

./scripts/banner "Processing lunarvim"

if ! command -v lvim > /dev/null; then
  if command -v nvim > /dev/null; then
    bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
  fi
fi
