#!/usr/bin/env bash


./scripts/banner "Processing lunarvim"

if ! command -v lvim > /dev/null; then
  if command -v nvim > /dev/null; then
    set +e
    bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
    set -e
  fi
fi

