#!/usr/bin/env bash

mkdir -p ~/.config/nvim

cd ~/.config
ln -sfv ~/.vim nvim
ln -sfv ~/.vimrc ~/.config/nvim/init.vim

curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing Neovim Bundles"
nvim +PlugInstall +qall
