#!/usr/bin/env bash

mkdir -p ~/.config/nvim

cd ~/.config
ln -sfv ~/.vim nvim
ln -sfv ~/.vimrc ~/.config/nvim/init.vim

curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing Neovim Bundles"
nvim +PlugInstall +qall

# echo "Installing Coc"
nvim -c ':CocInstall coc-css coc-json coc-html coc-solargraph coc-tsserver coc-go coc-lists'
nvim -c ':CocInstall coc-markdownlint coc-python coc-sh coc-snippets coc-yaml coc-sql coc-word coc-emoji'
nvim -c ':CocInstall coc-syntax coc-gocode coc-ultisnips coc-toml coc-dictionary coc-tag'
