#!/usr/bin/env bash

set -e

./scripts/banner "Processing neovim"

curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# echo "Installing Neovim Bundles"
# # nvim -u ~/.vimrc.bundles +PlugInstall +qall
#
# echo "Installing Coc"
# # this installs on startup
# nvim -u ~/.vimrc.bundles +PlugInstall +qall
