#!/bin/bash

if [[ $(uname) != Darwin ]]; then
  sudo apt-get install -y \
    ack-grep \
    axel \
    bar \
    bat \
    build-essential \
    curl \
    editorconfig \
    exuberant-ctags \
    fasd \
    fzf \
    git \
    git-extras \
    grc \
    htop \
    keychain \
    neovim \
    nodejs \
    npm \
    pv \
    silversearcher-ag \
    tmux \
    tree \
    vim-nox \
    wget \
    zsh
fi

if [[ $(uname) == Darwin ]]; then
  if type brew &> /dev/null; then
    brew tap homebrew/cask-fonts

    brew install \
      ack \
      axel \
      bar \
      bat \
      binutils \
      coreutils \
      cscope \
      ctags \
      curl \
      diff-so-fancy \
      editorconfig \
      exa \
      fasd \
      findutils \
      font-hack-nerd-font \
      fzf \
      git \
      git-extras \
      gnu-getopt \
      gnu-indent \
      gnu-sed \
      gnu-tar \
      gnu-time \
      gnu-which \
      gnupg \
      gnutls \
      gpg \
      gpg2 \
      grc \
      grep \
      htop-osx \
      hub \
      keychain \
      macvim \
      neovim \
      node \
      openssl \
      pinentry-mac \
      pv \
      readline \
      reattach-to-user-namespace \
      ripgrep \
      ssh-copy-id \
      the_silver_searcher \
      tidy-html5 \
      tmux \
      trash \
      tree \
      watch \
      wget \
      wrk \
      zsh

    pip3 install neovim
  fi
fi
