#!/bin/bash

if [[ $(uname) != Darwin ]]; then
  sudo apt-get install -y \
    ack-grep \
    axel
    bash-completion \
    build-essential \
    curl \
    editorconfig \
    exuberant-ctags \
    git \
    git-extras \
    grc \
    htop \
    keychain \
    nodejs \
    npm \
    pv \
    silversearcher-ag \
    tmux \
    tree \
    vim-nox
fi

if [[ $(uname) == Darwin ]]; then
  if type brew &> /dev/null; then
    brew install \
      ack \
      axel \
      bash-completion2 \
      ctags \
      curl \
      editorconfig \
      fasd \
      git \
      git-extras \
      gpg-agent \
      grc \
      grep \
      htop-osx \
      hub \
      keychain \
      macvim \
      node \
      pv \
      reattach-to-user-namespace \
      the_silver_searcher \
      tidy-html5 \
      tmux \
      trash \
      tree \
      watch \
      wrk
  fi
fi
