#!/bin/bash

if [ ! -d ~/.rbenv/shims ]; then
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
fi

linkable="`pwd -P`/rbenv/default-gems"
target=`~/.rbenv/default-gems`

ln -vsf "$linkable" "$target"

if [ ! -d ~/.rbenv/plugins/rbenv-ctags ]; then
  echo "Installing rbenv-ctags"
  git clone git://github.com/tpope/rbenv-ctags.git ~/.rbenv/plugins/rbenv-ctags
fi

if [ ! -d ~/.rbenv/plugins/rbenv-binstubs ]; then
  echo "Installing rbenv-binstubs"
  git clone git://github.com/ianheggie/rbenv-binstubs.git ~/.rbenv/plugins/rbenv-binstubs
fi
