#!/usr/bin/env bash

set -e

./scripts/banner "Processing rvim"

curl -fLo ~/.config/rvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing rvim Bundles"
NVIM_APPNAME=rvim nvim +PlugInstall +qall
