#!/bin/bash

mkdir -p ~/.solarized

if command -v gnome-terminal &> /dev/null; then
  if [ ! -d ~/.solarized/gnome-terminal ]; then
    git clone https://github.com/sigurdga/gnome-terminal-colors-solarized.git ~/.solarized/gnome-terminal
  fi

  ~/.solarized/gnome-terminal/set_dark.sh
fi

if [ ! -d ~/.solarized/official ]; then
  git clone https://github.com/altercation/solarized.git ~/.solarized/official
fi
