#!/usr/bin/env bash

set -e

echo "Processing solarized"

mkdir -p ~/.solarized

if [ ! -d ~/.solarized/gnome-terminal ]; then
  git clone https://github.com/sigurdga/gnome-terminal-colors-solarized.git ~/.solarized/gnome-terminal
fi

if command -v gnome-terminal &> /dev/null; then
  ~/.solarized/gnome-terminal/set_dark.sh
fi

if [ ! -d ~/.solarized/official ]; then
  git clone https://github.com/altercation/solarized.git ~/.solarized/official
fi
