#!/usr/bin/env bash

set -e

echo -e "\033[0;32m>>>>> Installing tmux <<<<<\033[0m"

if [ ! -d ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

~/.tmux/plugins/tpm/bin/install_plugins
