#!/bin/bash

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# git clone git://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
# cd ~/.vim/bundle/vundle && git pull

echo "Installing Vim Bundles"
# vim +PluginInstall! +PluginClean! +qall
vim +PlugInstall +qall

echo "Installing NeoVim Bundles"
# vim +PluginInstall! +PluginClean! +qall
nvim +PlugInstall +qall
