#!/usr/bin/env bash

set -e

echo "Processing vim"

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing Vim Bundles"
vim -u ~/.vimrc.bundles +PlugInstall +qall

echo "Installing Coc"
# this installs on startup
vim -u ~/.vimrc.bundles +PlugInstall +qall
