#!/usr/bin/env bash

echo "Installing Node modules for Vim Syntastic checks"
please=
if [[ $(uname) != Darwin ]]; then
  if command -v sudo &> /dev/null; then
    please=sudo
  fi
fi

$please npm install -g babel-eslint
$please npm install -g csslint
$please npm install -g eslint
$please npm install -g eslint-plugin-react
$please npm install -g js-yaml
$please npm install -g jshint
$please npm install -g jsonlint
$please npm install -g jsxhint
$please npm install -g react-tools
$please npm install -g syntastic-react
$please npm install -g instant-markdown-d
