#!/bin/bash

echo "Installing Node modules for Vim Syntastic checks"
npm install -g babel-eslint
npm install -g csslint
npm install -g eslint
npm install -g eslint-plugin-react
npm install -g js-yaml
npm install -g jshint
npm install -g jsonlint
npm install -g jsxhint
npm install -g react-tools
npm install -g syntastic-react
