#!/usr/bin/env bash

set -e

echo -e "\033[0;32m>>>>> Installing vim-node-modules <<<<<\033[0m"

please=
if [[ $(uname) != Darwin ]]; then
  if command -v sudo &> /dev/null; then
    please=sudo
  fi
fi

$please npm install -g babel-eslint
$please npm install -g csslint
$please npm install -g eslint
$please npm install -g eslint-plugin-react
$please npm install -g js-yaml
$please npm install -g jshint
$please npm install -g jsonlint
$please npm install -g jsxhint
$please npm install -g react-tools
$please npm install -g syntastic-react
$please npm install -g instant-markdown-d
