#!/usr/bin/env bash

set -e

echo "Processing zsh"

if [ ! -d ~/.zi ]; then
  echo 'Installing zi'
  git clone https://github.com/z-shell/zi.git ~/.zi/bin
  mkdir -p ~/.cache/zi/completions
fi

if [ ! -z "$ZSH_CACHE_DIR" ] ; then
  mkdir -p $ZSH_CACHE_DIR/completions
fi
