#!/bin/bash

hamster-cli stop
notify-send "Off the clock"
purple-remote 'setstatus?status=offline'
sleep 5
gnome-screensaver-command -l

zenity --info --text "Click OK to clock in"
hamster-cli start tukios
notify-send "On the clock"
purple-remote 'setstatus?status=online'
