FROM ubuntu as base

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ack-grep \
    atop \
    axel \
    bar \
    bat \
    build-essential \
    curl \
    dstat \
    editorconfig \
    exa \
    exuberant-ctags \
    fasd \
    fzf \
    git \
    git-extras \
    grc \
    htop \
    ioping \
    iotop \
    keychain \
    neovim \
    nodejs \
    npm \
    pv \
    python3-pip \
    ranger \
    ripgrep \
    silversearcher-ag \
    sudo \
    tmux \
    tree \
    vim-nox \
    wget \
    zsh

RUN useradd --create-home --home-dir /home/tester --shell /usr/bin/bash -p $(perl -e 'print crypt($ARGV[0], "password")' 'test') tester
RUN adduser tester sudo

WORKDIR /home/tester

COPY docker-entrypoint.sh ./

USER tester

# This script will run anytime this docker image starts
ENTRYPOINT ["/home/tester/docker-entrypoint.sh"]

CMD "/usr/bin/bash"
