FROM ubuntu as base

RUN apt-get update
RUN apt-get install git sudo --assume-yes

RUN useradd --create-home --home-dir /home/tester --shell /usr/bin/bash -p $(perl -e 'print crypt($ARGV[0], "password")' 'test') tester
RUN adduser tester sudo

WORKDIR /home/tester

COPY docker-entrypoint.sh ./

USER tester

# This script will run anytime this docker image starts
ENTRYPOINT ["/home/tester/docker-entrypoint.sh"]

CMD "/usr/bin/bash"
