vim.opt.backup = false
vim.opt.clipboard = "unnamedplus"
vim.opt.cmdheight = 2         -- Cmd bar 2 rows high
vim.opt.complete = '.,w,b,u,t'
vim.opt.completeopt = 'menu,preview'
vim.opt.cursorline = true            -- highlight current line - slow
vim.opt.errorbells = false        -- No noise
vim.opt.expandtab = true           -- Use spaces not tabs
vim.opt.exrc = true                -- allow local .vimrc files per project
vim.opt.foldenable = false
vim.opt.foldlevel = 1
vim.opt.foldlevelstart = 99
vim.opt.foldmethod = 'syntax' --even with nofoldenable foldmethod=syntax causes slow ins-completions"
vim.opt.foldnestmax = 10
vim.opt.guifont = 'DroidSansMono Nerd Font 11'
vim.opt.ignorecase = true
vim.opt.infercase = true
vim.opt.joinspaces = false       -- Use only 1 space after "." when joining lines instead of 2
vim.opt.linebreak = true           -- Don't wrap text in the middle of a word
vim.opt.list = true
vim.opt.matchtime= 2         -- for .2 seconds
vim.opt.maxmempattern = 5000
vim.opt.number = true              -- Show line numbers
vim.opt.numberwidth = 1        -- Try to use only 1 col when possible
vim.opt.scrolloff = 5          -- Keep 5 lines (top/bottom) for scope
vim.opt.shiftwidth = 2        -- Indent level is 2 spaces wide
vim.opt.shortmess = 'astIF'      -- The "Press ENTER or type command to continue" prompt is jarring and usually unnecessary.
vim.opt.showmatch = true            -- Show matched paren when balanced
vim.opt.showtabline = 2
vim.opt.signcolumn = 'yes' -- Always show the signcolumn, otherwise it would shift the text each time diagnostics appear/become resolved. for coc
vim.opt.smartcase  = true -- make searches case-sensitive only if they contain upper-case characters
vim.opt.smartindent = true
vim.opt.softtabstop = 2       -- <BS> over an autoindent deletes shiftwidth worth of spaces
vim.opt.spell = true
vim.opt.spelllang = { 'en_us' }
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.startofline = false       -- Don't reset cursor to start of line when moving around
vim.opt.swapfile = false
vim.opt.synmaxcol = 1200      -- Syntax coloring lines that are too long just slows down the world
vim.opt.tabstop = 2           -- Use 2 spaces for <tab>
vim.opt.tagbsearch = true          -- use binary searching for tags
vim.opt.tags = { "./tags", "./ruby-tags", "./.git/tags", "~/.rbenv/tags" }
vim.opt.termguicolors = true
vim.opt.timeout = true
vim.opt.timeoutlen = 400
vim.opt.ttimeout  = true
vim.opt.ttimeoutlen = 300
vim.opt.undofile = true
vim.opt.undolevels = 1000
vim.opt.undoreload = 10000
vim.opt.updatetime = 300 -- Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable delays and poor user experience.
vim.opt.visualbell = false
vim.opt.wildignore = { "*/tmp/*", "*/.git/*", "*.so", "*.swp", "*.zip", "*/log/*" }
vim.opt.wrap = false
vim.opt.writebackup = false
